/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;


public class Profile extends javax.swing.JInternalFrame {
   Connection con=null;
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        abc = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        contactbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        namebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        genderbox = new javax.swing.JTextField();
        departmentbox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        passwordbox = new javax.swing.JPasswordField();
        type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setTitle("Create Profile");
        setPreferredSize(new java.awt.Dimension(725, 515));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        abc.setBackground(new java.awt.Color(153, 255, 153));
        abc.setPreferredSize(new java.awt.Dimension(725, 500));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("User name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Contact number");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Department id");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("User id");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Email Address");

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_create_new3_64px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });

        departmentbox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        departmentbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select department id", "001", "002", "003" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "lecture", "student", "technical_officer" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("User type");

        javax.swing.GroupLayout abcLayout = new javax.swing.GroupLayout(abc);
        abc.setLayout(abcLayout);
        abcLayout.setHorizontalGroup(
            abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abcLayout.createSequentialGroup()
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abcLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(abcLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(48, 48, 48))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(abcLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(departmentbox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactbox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderbox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordbox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abcLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userbox)
                                .addGroup(abcLayout.createSequentialGroup()
                                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 32, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abcLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );
        abcLayout.setVerticalGroup(
            abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(abcLayout.createSequentialGroup()
                        .addComponent(userbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abcLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6))
                            .addGroup(abcLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(departmentbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactbox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(abcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abcLayout.createSequentialGroup()
                        .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(passwordbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abcLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
            .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String utype=type.getSelectedItem().toString();
        String id=userbox.getText();
        String depart=departmentbox.getSelectedItem().toString();
        String name=namebox.getText();
        String email=emailbox.getText();
        String contact=contactbox.getText();
        String gender=genderbox.getText();
        String pass=passwordbox.getText();
       
        
        
        
        switch(utype){
            case "admin":
                
        try{
            con=DBConnect.connect();
            String q= "INSERT INTO admin(adm_id,d_id,adm_name,adm_email,adm_contact,gender,pasword) values('"+id+"','"+depart+"','"+name+"','"+email+"','"+contact+"','"+gender+"','"+pass+"')";
            PreparedStatement pst = con.prepareStatement(q);
            pst.execute();
            
        }

        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, e);

        }
        
       //  String us=userbox.getText();
         
       
          
         
                break;
                
                
            case "lecture":
                
            try{
            con=DBConnect.connect();
            String q= "INSERT INTO lecturer(lec_id,d_id,lec_name,lec_email,lec_contact,gender,password) values('"+id+"','"+depart+"','"+name+"','"+email+"','"+contact+"','"+gender+"','"+pass+"')";
            PreparedStatement pst = con.prepareStatement(q);
            pst.execute();
            
        }

        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, e);

        }

                /* String use=userbox.getText();
                 String passw=passwordbox.getText();

                 try{
                    con=DBConnect.connect();
                    String r= "INSERT INTO user(lec_id,password) values('"+use+"','"+passw+"')";
                    PreparedStatement pst = con.prepareStatement(r);
                    pst.execute();

                }

                catch(SQLException e){
                    javax.swing.JOptionPane.showMessageDialog(null, e);

                }
                */
                break;
                
                
                
            case "student":

                try{
                    con=DBConnect.connect();
                    String q= "INSERT INTO student(s_id,d_id,s_name,s_email,s_contact,gender,password) values('"+id+"','"+depart+"','"+name+"','"+email+"','"+contact+"','"+gender+"','"+pass+"')";
                    PreparedStatement pst = con.prepareStatement(q);
                    pst.execute();

                }

                catch(SQLException e){
                    javax.swing.JOptionPane.showMessageDialog(null, e);

                }

                 /*String users=userbox.getText();
                 String passws=passwordbox.getText();

                 try{
                    con=DBConnect.connect();
                    String r= "INSERT INTO user(s_id,password) values('"+users+"','"+passws+"')";
                    PreparedStatement pst = con.prepareStatement(r);
                    pst.execute();

                }

                catch(SQLException e){
                    javax.swing.JOptionPane.showMessageDialog(null, e);

                }*/


                        break;
                        
                        
                  case "technical_officer":

                try{
                    con=DBConnect.connect();
                    String q= "INSERT INTO technical_officer(tec_id,d_id,tec_name,tec_email,tec_contact,gender,password) values('"+id+"','"+depart+"','"+name+"','"+email+"','"+contact+"','"+gender+"','"+pass+"')";
                    PreparedStatement pst = con.prepareStatement(q);
                    pst.execute();

                }

                catch(SQLException e){
                    javax.swing.JOptionPane.showMessageDialog(null, e);

                }

                 /*String usert=userbox.getText();
                 String passt=passwordbox.getText();

                 try{
                    con=DBConnect.connect();
                    String r= "INSERT INTO user(s_id,password) values('"+usert+"','"+passt+"')";
                    PreparedStatement pst = con.prepareStatement(r);
                    pst.execute();

                }

                catch(SQLException e){
                    javax.swing.JOptionPane.showMessageDialog(null, e);

                }

*/
                        break;
        
    }

        

              
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abc;
    private javax.swing.JTextField contactbox;
    private javax.swing.JComboBox<String> departmentbox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JTextField genderbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField namebox;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField userbox;
    // End of variables declaration//GEN-END:variables
}
