/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CA2 extends javax.swing.JInternalFrame {
                Connection conn = null;
              PreparedStatement psd = null;
    /**
     * Creates new form CA2
     */
    public CA2() {
        initComponents();
         conn = dbconnect.connect();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jQ1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jQ2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jQ3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jAss1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jAss2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jQ4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jIndexNo = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Marks Here");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, 216, 53));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Index_number: ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 129, 177, 39));
        getContentPane().add(jQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 192, 58, 39));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Q2");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 189, 49, 39));
        getContentPane().add(jQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 192, 62, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Q3");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 189, 49, 39));
        getContentPane().add(jQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 192, 54, 39));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Assessment 1");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 268, 127, 39));
        getContentPane().add(jAss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 271, 122, 39));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText(" Assessment 2");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 328, -1, 39));
        getContentPane().add(jAss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 331, 122, 39));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mid");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 388, -1, 39));
        getContentPane().add(jMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 391, 122, 39));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Final Theory");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 461, -1, 39));
        getContentPane().add(jFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 464, 122, 39));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Q4");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 189, 49, 39));
        getContentPane().add(jQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 192, 53, 39));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Q1");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 189, 49, 39));
        getContentPane().add(jIndexNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 132, 122, 39));

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 463, 83, 41));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 462, 86, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/light-blue-abstract-wallpaper-19.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertMarks(){
        String st_no = jIndexNo.getText();
String Q1 = jQ1.getText();
Integer.parseInt(Q1);
String Q2 = jQ2.getText();
Integer.parseInt(Q2);
String Q3 = jQ3.getText();
Integer.parseInt(Q3);
String Q4 = jQ4.getText();
Integer.parseInt(Q4);
String A1 = jAss1.getText();
Integer.parseInt(A1);
String A2 = jAss2.getText();
Integer.parseInt(A2);
String mid = jMid.getText();
Integer.parseInt(mid);
String f_theory = jFT.getText();
Integer.parseInt(f_theory);

        int p= JOptionPane.showConfirmDialog(null, "Are you sure want to add ?", "Add Marks", JOptionPane.YES_NO_OPTION);
            if(p==0){
                try {
                    String qu = "INSERT INTO economics(s_id,Q1,Q2,Q3,Q4,A2,A1,mid,f_theory)values('"+st_no+"','"+Q1+"','"+Q2+"','"+ Q3+"','"+Q4 +"','"+A1+"','"+A2+"','"+ mid+"','"+f_theory+"')";
                    psd = conn.prepareStatement(qu);
                    psd.execute();
                    JOptionPane.showMessageDialog(null,"Inseted successfully");
                }catch (SQLException ex) {
                    Logger.getLogger(CA11.class.getName()).log(Level.SEVERE, null, ex);
                }
            }   
    }
    
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
            insertMarks();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                    jIndexNo.setText("");
                    jQ1.setText("");
                    jQ2.setText("");
                    jQ3.setText("");
                    jQ4.setText("");
                    jAss1.setText("");
                    jAss2.setText("");
                    jMid.setText("");
                    jFT.setText("");           
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JTextField jAss1;
    private javax.swing.JTextField jAss2;
    private javax.swing.JTextField jFT;
    private javax.swing.JTextField jIndexNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jMid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQ1;
    private javax.swing.JTextField jQ2;
    private javax.swing.JTextField jQ3;
    private javax.swing.JTextField jQ4;
    // End of variables declaration//GEN-END:variables
}
