/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CA3 extends javax.swing.JInternalFrame {
        Connection conn = null;
        PreparedStatement psd = null;
       
    /**
     * Creates new form CA3
     */
    public CA3() {
        initComponents();
        conn = dbconnect.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jQ2 = new javax.swing.JTextField();
        jFT = new javax.swing.JTextField();
        jFP = new javax.swing.JTextField();
        jQ1 = new javax.swing.JTextField();
        jAss2 = new javax.swing.JTextField();
        jAss1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jAss3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jQ3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jIndexNo = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Marks Here");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 31, 216, 53));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Q1");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 171, 49, 39));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Q2");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 171, 49, 39));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Assessment 1");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 268, 127, 39));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText(" Assessment 2");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 339, -1, 39));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Final Practical");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 473, -1, 39));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Final Theory");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 473, -1, 39));
        getContentPane().add(jQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 174, 53, 39));
        getContentPane().add(jFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 476, 122, 39));
        getContentPane().add(jFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 476, 122, 39));
        getContentPane().add(jQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 174, 54, 39));
        getContentPane().add(jAss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 342, 122, 39));
        getContentPane().add(jAss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 271, 122, 39));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Assessment 3");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 404, 127, 39));
        getContentPane().add(jAss3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 407, 122, 39));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Q3");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 171, -1, 39));
        getContentPane().add(jQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 174, 49, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Index number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 102, 159, 37));
        getContentPane().add(jIndexNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 106, 165, 35));

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 409, 83, 35));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 409, 77, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/light-blue-abstract-wallpaper-19.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void insertMarks() {
        String st_no = jIndexNo.getText();
        String Q1 = jQ1.getText();
        Integer.parseInt(Q1);
        String Q2 = jQ2.getText();
        Integer.parseInt(Q2);
        String Q3 = jQ3.getText();
        Integer.parseInt(Q3);
        String A1 = jAss1.getText();
        Integer.parseInt(A1);
        String A2 = jAss2.getText();
        Integer.parseInt(A2);
        String A3 = jAss3.getText();
        Integer.parseInt(A3);
        String f_theory = jFT.getText();
        Integer.parseInt(f_theory);
        String f_prac = jFP.getText();
        Integer.parseInt(f_prac);

        int p= JOptionPane.showConfirmDialog(null, "Are you sure want to add ?", "Add Marks", JOptionPane.YES_NO_OPTION);
        if(p==0){
            try {
                String qu = "INSERT INTO ood(s_id,Q1,Q2,Q3,A1,A2,A3,f_theory,f_practicle)values('"+st_no+"','"+Q1+"','"+Q2+"','"+ Q3+"','"+A1+"','"+A2+"','"+ A3+"','"+f_theory+"','"+f_prac+"')";
                psd = conn.prepareStatement(qu);
                psd.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted successfully");
            }catch (SQLException ex) {
                Logger.getLogger(CA11.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }
    
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insertMarks();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
                    jIndexNo.setText("");
                    jQ1.setText("");
                    jQ2.setText("");
                    jQ3.setText("");
                    jAss1.setText("");
                    jAss2.setText("");
                    jAss3.setText("");
                    jFT.setText("");
                    jFP.setText("");
                    
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JTextField jAss1;
    private javax.swing.JTextField jAss2;
    private javax.swing.JTextField jAss3;
    private javax.swing.JTextField jFP;
    private javax.swing.JTextField jFT;
    private javax.swing.JTextField jIndexNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jQ1;
    private javax.swing.JTextField jQ2;
    private javax.swing.JTextField jQ3;
    // End of variables declaration//GEN-END:variables


}
