/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer;

import Admins.DBConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public final class Details extends javax.swing.JInternalFrame {

    /**
     * Creates new form Details
     */
    PreparedStatement psd= null;
    ResultSet rs = null;
    Connection conn = null;
    Statement st = null;
    
    
    public Details() { 
        initComponents();
       
        findUsers();
    }
    
    

    /*public ArrayList<Student> userList(){
        ArrayList<Student> usersList = new ArrayList<>();
            try{
                 Class.forName("com.mysql.jdbc.Driver");
                 conn = dbconnect.connect();
                 String query1="SELECT * from student";
                 st= conn.createStatement();
                 rs = st.executeQuery(query1);
                 Student  student;
                 while(rs.next()){
                     student = new Student(rs.getString("s_id"),rs.getString("d_id"),rs.getString("s_name"),rs.getString("s_dob"),rs.getString("gender"));
                     usersList.add(student);
                 }
            }
            catch(Exception e){
                System.out.println(e);
             }
           return usersList;
     }
     public void showStudent(){
        ArrayList<Student> list = userList();
         DefaultTableModel model = (DefaultTableModel)jTable_Display_Student.getModel();
         Object[] row = new Object[5];
         for (int i = 0; i < list.size();i++) {
                row[0]=list.get(i).getSid();
                row[1]=list.get(i).getDid();
                row[2]=list.get(i).getName();
                row[3]=list.get(i).getDOB();
                row[4]=list.get(i).getGender();
                model.addRow(row);
         }
      
        
        
     }*/
      public ArrayList<Student> ListUser(String valToSearch){
          ArrayList<Student> ListUsers = new ArrayList<Student>();
          
          try {
              Class.forName("com.mysql.jdbc.Driver");
              conn = DBConnect.connect();
              st = conn.createStatement();
              String query2 = "SELECT * FROM `students` WHERE CONCAT(`s_id`,`d_id`,`s_name`,`s_dob`,`gender`)LIKE '%"+valToSearch+"%'";
              rs = st.executeQuery(query2);
              Student student;
              while(rs.next()){
                  student = new Student(rs.getString("s_id"),rs.getString("d_id"),rs.getString("s_name"),rs.getString("s_dob"),rs.getString("gender"));
                  ListUsers.add(student);
              }
          } catch (Exception e) {
          }
          
         return ListUsers;
      }
      public void findUsers(){
          ArrayList<Student> foundedUser = ListUser(jDseach.getText());
          DefaultTableModel models = new DefaultTableModel();
          models.setColumnIdentifiers(new Object[]{"Student_id","Dept_id","Student_name","DOB","Gender"});
          
          
          Object[] row = new Object[5];
            for (int i = 0; i < foundedUser.size();i++) {
                row[0]=foundedUser.get(i).getSid();
                row[1]=foundedUser.get(i).getDid();
                row[2]=foundedUser.get(i).getName();
                row[3]=foundedUser.get(i).getDOB();
                row[4]=foundedUser.get(i).getGender();
                models.addRow(row);
            }
          jTable_Display_Student.setModel(models);
                  
      }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsearchDetails = new javax.swing.JButton();
        jDseach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Student = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsearchDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jsearchDetails.setText("Search");
        jsearchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jsearchDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, 30));

        jDseach.setText("TG");
        jDseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDseachActionPerformed(evt);
            }
        });
        jPanel1.add(jDseach, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 30));

        jTable_Display_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_id", "Dep_id", "Student_name", "DOB", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_Student);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 600, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Student Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/light-blue-abstract-wallpaper-19.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDseachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDseachActionPerformed

    private void jsearchDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchDetailsActionPerformed
                findUsers();
    }//GEN-LAST:event_jsearchDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDseach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Student;
    private javax.swing.JButton jsearchDetails;
    // End of variables declaration//GEN-END:variables
}
