/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer;

/**
 *
 * @author Dell
 */
public class Marks extends javax.swing.JInternalFrame {

    /**
     * Creates new form Marks
     */
    public Marks() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMarkspane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jChoose_course = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jMarkspaneLayout = new javax.swing.GroupLayout(jMarkspane);
        jMarkspane.setLayout(jMarkspaneLayout);
        jMarkspaneLayout.setHorizontalGroup(
            jMarkspaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        jMarkspaneLayout.setVerticalGroup(
            jMarkspaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        jChoose_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Course", "TCS2122", "ENG2122", "ICT2123", "ICT2153", "ICT2113", "ICT2133" }));
        jChoose_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChoose_courseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChoose_course, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jChoose_course, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMarkspane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMarkspane)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChoose_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChoose_courseActionPerformed
               if(jChoose_course.getSelectedItem().equals("TCS2122")){
                     CA2 sft = new CA2();
                     jMarkspane.add(sft).setVisible(true);
                     
                  
               }
               else if(jChoose_course.getSelectedItem().equals("ICT2113")){
                   
                   CA11 sft1 = new CA11();
                   
                   jMarkspane.add(sft1).setVisible(true);
                   sft1.setVisible();
                   
               }
               else if(jChoose_course.getSelectedItem().equals("ICT2133")){
                     CA12 sft = new CA12();
                     jMarkspane.add(sft).setVisible(true);
                  
               }
               
               else if(jChoose_course.getSelectedItem().equals("ICT2123")){
                   
                   CA3 sft2 = new CA3();
                   jMarkspane.add(sft2).setVisible(true);
                   
               }
                else if(jChoose_course.getSelectedItem().equals("ICT2153")){
                   
                   CA31 sft2 = new CA31();
                   jMarkspane.add(sft2).setVisible(true);
                   
               }
               else{
                   CA4 sft3 = new CA4();
                   jMarkspane.add(sft3).setVisible(true);
               }
               
                
    }//GEN-LAST:event_jChoose_courseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jChoose_course;
    private javax.swing.JDesktopPane jMarkspane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
